### ISSUE TITLE
wrong values in time_fi

### ISSUE THREAD

**Issue by kmexter** [emo-bon/observatory-roskogo-crate#10]
https://docs.google.com/spreadsheets/d/1BCu2pbuIS4f-yrw5Kw4uzfO9v6ryZJBtSF5WBLWG_-E/edit?gid=158762518#gid=158762518
the values in time_fi are wrong - they should be in hours, not an actual time

**Comment by melinalou** [comment]
do you meen that for example this 2021-06-18T12:00+02:00 should be 12?

**Comment by kmexter** [comment]
it should be the number of hours the filtration took, not the time it happened at
I think here they mean 2 hrs?

**Comment by melinalou** [comment]
maybe I can make the convertion for all and if they do not mean this to ask them to fill in the correct information?

**Comment by kmexter** [comment]
yes you can make a global change and then ask them if that is what they meant

**Comment by melinalou** [comment]
done

**Comment by kmexter** [comment]
closing

**Comment by kmexter** [comment]
closing
