### ISSUE TITLE
Empty lines in files

### ISSUE THREAD

**Issue by cpavloud** [emo-bon/observatory-roskogo-crate#3]
It is very unpractical to have empty lines in the logsheets (e.g. in https://github.com/emo-bon/observatory-roskogo-crate/blob/main/logsheets/transformed/sediment_sampling.csv and https://github.com/emo-bon/observatory-roskogo-crate/blob/main/logsheets/transformed/sediment_measured.csv).
Also, it is inconsistent with similar files from other observatories. 

@melinalou

**Comment by melinalou** [comment]
by empty lines you mean empty cells?

**Comment by cpavloud** [comment]
No, I mean lines. In the end of the files, there are several empty lines.

**Comment by melinalou** [comment]
Yes I am sorry.
I don't have the permission to delete them.

**Comment by cpavloud** [comment]
@melanthia can you?

**Comment by cpavloud** [comment]
I think this is not the case anymore, so I am closing the issue
